# Configuração do banco de dados H2 em modo servidor
spring.datasource.url=jdbc:h2:tcp://localhost:9092/~/test;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create

# Log de SQL e exceções (detalhado para desenvolvimento)
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Configuração do Spring DevTools para recarregamento automático
spring.devtools.restart.enabled=true

# Habilitar o console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console